services:
  api:
    build:
      context: ./api
    develop:
      watch:
        - action: sync
          path: ./api/
          target: /app/
        - action: rebuild
          path: ./api/package.json
    command: pnpm dev
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DEPS_HOME_DOMAIN: deps.rubixdev.net
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - deps-home-net

  frontend:
    build:
      context: ./frontend
      target: dev
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/
    command: pnpm dev --host 0.0.0.0
    ports:
      - "5173:5173"
    networks:
      - deps-home-net

  db:
    image: postgres:16
    container_name: deps-home-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - deps-home-net

volumes:
  db-data:

networks:
  deps-home-net:
